excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - OLD
  - lib
  
opt_in_rules:
  - force_unwrapping
  
force_unwrapping: error

function_parameter_count:
    error: 6

cyclomatic_complexity:
    warning: 10
    error: 15

nesting: error
  
line_length: 
    warning: 170
    error: 200
    
type_body_length: 
  warning: 500
  error: 600
  
file_length:
  warning: 750
  error: 900
  
